function varargout = GoMouse_z_export(varargin)
% GOMOUSE_Z_EXPORT MATLAB code for GoMouse_z_export.fig
%      GOMOUSE_Z_EXPORT, by itself, creates a new GOMOUSE_Z_EXPORT or ra-`    ises the existing
%      singleton*.
%
%      H = GOMOUSE_Z_EXPORT returns the handle to a new GOMOUSE_Z_EXPORT or the handle to
%      the existing singleton*.
%
%      GOMOUSE_Z_EXPORT('CALLBACK',hObjec  t,eventData,handles,...) calls the local
%      function named CALLBACK in GOMOUSE_Z_EXPORT.M with the given input arguments.
%
%      GOMOUSE_Z_EXPORT('Property','Value',...) creates a new GOMOUSE_Z_EXPORT or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before GoMouse_z_export_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to GoMouse_z_export_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% Edit the above text to modify the response to help GoMouse_z_export

% Last Modified by GUIDE v2.5 08-Aug-2023 17:01:39

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
    'gui_Singleton',  gui_Singleton, ...
    'gui_OpeningFcn', @GoMouse_z_export_OpeningFcn, ...
    'gui_OutputFcn',  @GoMouse_z_export_OutputFcn, ...
    'gui_LayoutFcn',  @GoMouse_z_export_LayoutFcn, ...
    'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT



%% SET VARIABLES
global pm
pm.stimFolder = 'D:\stimuli\';
pm.mouseFolder = 'D:\data\';
pm.filterFolder = 'D:\GitHub\filters\';


% --- Executes just before GoMouse_z_export is made visible.
function GoMouse_z_export_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to GoMouse_z_export (see VARARGIN)

% Choose default command line output for GoMouse_z_export
handles.output = hObject;

% Update handles structure
global pm
guidata(hObject, handles);
set(hObject,'Name','GoMouse!')
pm.wavFolders = [];
set(handles.blocktable,'Data',[])

% UIWAIT makes GoMouse_z_export wait for user response (see UIRESUME)
% uiwait(handles.figure1);




% --- Outputs from this function are returned to the command line.
function varargout = GoMouse_z_export_OutputFcn(hObject, eventdata, handles)
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Get default command line output from handles structure
varargout{1} = handles.output;






%% SELECT YOUR BEAST
function mouselist_Callback(hObject, eventdata, handles) %#ok<*INUSD>
global pm
contents = cellstr(get(hObject,'String'));
pm.mouse = contents{get(hObject,'Value')};
handles.status.String = sprintf('Mouse selected: %s',pm.mouse);
pm.saveFolder = [pm.mouseFolder pm.mouse '\'];


% POPULATE SELECT YOUR BEAST
function mouselist_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% Populate the listbox
global pm
f = dir(pm.mouseFolder);
f(strcmp({f.name},'.'))=[]; f(strcmp({f.name},'..'))=[]; f(strcmp({f.name},'zippedEventTraces'))=[];
f = {f.name};
set(hObject,'string',f);
set(hObject,'Value',length(f));
contents = cellstr(get(hObject,'String'));
pm.mouse = contents{get(hObject,'Value')};




%% SELECT FOLDER
function folderlist_Callback(hObject, eventdata, handles)
global pm
contents = cellstr(get(hObject,'String'));
pm.person = contents{get(hObject,'Value')};

% Populate the PROJECT listbox
populateProjectFolderListbox(handles)




% POPULATE SELECT FOLDER
function folderlist_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% Populate the listbox
global pm
f = dir(pm.stimFolder);
f(strcmp({f.name},'.'))=[]; f(strcmp({f.name},'..'))=[];
f = {f.name};
set(hObject,'string',f);
hObject.Value = 1;
contents = cellstr(get(hObject,'String'));
pm.person = contents{get(hObject,'Value')};




%% SELECT PROJECT FOLDER
function projectlist_Callback(hObject, eventdata, handles)
populateSelectStimListbox(handles);


% POPULATE PROJECT FOLDER
function projectlist_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


%% SELECT STIMULI LISTBOX
function stimlist_Callback(hObject, eventdata, handles)

% POPULATE SELECT STIMULI
function stimlist_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


%% EDIT BLOCKS NUMBERS
function blocktable_ButtonDownFcn(hObject, eventdata, handles)
wavs = cellstr(get(handles.stimselectlist,'String'));
d = get(handles.blocktable,'Data');
editBlockNumbers(wavs,d,handles);


%% ADD PUSH BUTTON
function addstim_Callback(hObject, eventdata, handles)
global pm
contents = cellstr(get(handles.stimselectlist,'String'));
wavSel = get(handles.stimlist,'Value');
wavsToAdd = cellstr(get(handles.stimlist,'String'));
wavsToAdd = wavsToAdd(wavSel);
if strcmp(contents,'Listbox')
    contents=wavsToAdd;
else
    contents(length(contents)+1:length(contents)+length(wavsToAdd)) = wavsToAdd;
end
%  pm.wavsToPresent
set(handles.stimselectlist,'String',contents)
set(handles.stimselectlist,'Max',length(contents),'Min',1);
for ii=1:length(wavsToAdd)
    pm.wavFolders{length(pm.wavFolders)+1,1} = pm.wavDir;
end
% edit block numbers
d = get(handles.blocktable,'Data');
a = get(handles.stimselectlist,'Value');
if ~iscell(d)
    d=num2cell(d);
end
if ~isempty(d)
    nd = cat(1,d,cat(2,repmat(d(a,1),length(wavsToAdd),1),num2cell(ones(length(wavsToAdd),1))));
else
    nd = ones(length(wavsToAdd),2);
end
set(handles.blocktable,'Data',nd)



%% REMOVE PUSH BUTTON
function removestim_Callback(hObject, eventdata, handles)
global pm
contents = cellstr(get(handles.stimselectlist,'String'));
if length(contents)==1
    contents{1} = 'Listbox';
else
    rm = get(handles.stimselectlist,'Value');
    if rm(1)-1<1
        set(handles.stimselectlist,'Value',1);
    else
        set(handles.stimselectlist,'Value',rm(1)-1);
    end
    contents(rm)=[];
    if isempty(contents)
        contents{1} = 'Listbox';
    end
end
pm.wavFolders(rm)=[];
set(handles.stimselectlist,'String',contents) 
set(handles.stimselectlist,'Max',length(contents),'Min',1);

d = get(handles.blocktable,'Data');
if ~isempty(d)
    d(rm,:)=[]; nd=d;
end
set(handles.blocktable,'Data',nd)




%% CLEAR ALL PUSH BUTTON
function clearstim_Callback(hObject, eventdata, handles)
global pm
set(handles.stimselectlist,'Value',1)
set(handles.stimselectlist,'String','Listbox')
pm.wavFolders=[];
set(handles.blocktable,'Data',[]);



%% STIMULI SELECTED LISTBOX
function stimselectlist_Callback(hObject, eventdata, handles)
% POPULATE STIMULI SELECTED
function stimselectlist_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


%% MOVE UP PUSH BUTTON
function movestimup_Callback(hObject, eventdata, handles)
global pm
contents = cellstr(get(handles.stimselectlist,'String'));
mu = get(handles.stimselectlist,'Value');
d = get(handles.blocktable,'Data');
if mu~=1
    newContents = [contents(1:mu(1)-2);contents(mu);contents(mu(1)-1);contents(mu(end)+1:end)];
    pm.wavFolders = cat(1,pm.wavFolders(1:mu(1)-2),pm.wavFolders(mu),pm.wavFolders(mu(1)-1),pm.wavFolders(mu(end)+1:end));
    d = cat(1,d(1:mu(1)-2,:),d(mu,:),d(mu(1)-1,:),d(mu(end)+1:end,:));
    set(handles.stimselectlist,'String',newContents)
    set(handles.stimselectlist,'Value',mu-1)
    set(handles.blocktable,'Data',d)
end



%% MOVE DOWN PUSH BUTTON
function movestimdown_Callback(hObject, eventdata, handles) %#ok<*INUSL,*DEFNU>
global pm
contents = cellstr(get(handles.stimselectlist,'String'));
mu = get(handles.stimselectlist,'Value');
d = get(handles.blocktable,'Data');
if mu~=length(contents)
    newContents = [contents(1:mu(1)-1);contents(mu(end)+1);contents(mu);contents(mu(end)+2:end)];
    pm.wavFolders = cat(1,pm.wavFolders(1:mu(1)-1),pm.wavFolders(mu(end)+1),pm.wavFolders(mu),pm.wavFolders(mu(end)+2:end));
    d = cat(1,d(1:mu(1)-1,:),d(mu(end)+1,:),d(mu,:),d(mu(end)+2:end,:));
    set(handles.stimselectlist,'String',newContents)
    set(handles.stimselectlist,'Value',mu+1)
    set(handles.blocktable,'Data',d)
end


%% RANDOMISE STIMULI ORDER
function randstim_Callback(hObject, eventdata, handles)
global pm
contents = cellstr(get(handles.stimselectlist,'String'));
d = get(handles.blocktable,'Data');
r = randperm(length(contents));
contents = contents(r);
pm.wavFolders = pm.wavFolders(r);
set(handles.stimselectlist,'String',contents)
set(handles.blocktable,'Data',d(r,:));







%% NOISE CLICKS TOGGLE BUTTON
function noiseclicks_Callback(hObject, eventdata, handles)
global nc
% clear -global nc
state = logical(get(hObject,'Value'));
if state
    % noise click stats
    dur = .5; % time in secs of click train
    duty = .25; % percentage of time the click will be on during rate cycle
    rate = 10; % number of times a click will play per second
    ISI = .5; % time in secs between click trains
    reps = 2; % number of click trains per event
    fs = str2double(get(handles.samplerate,'String'));
    filtName = get(handles.filterfile,'String');
%     load(filtName);
    FILT = [];
    noise = makeClicks(fs,duty,rate,dur,ISI,reps,FILT); % duration, ISI and sample rate
    set(handles.status,'String','Connecting to NIDAQ card');
    nc.s = connectToNidaq(fs,[],[0,1]);
    set(handles.status,'String','NIDAQ connected');
%     nc.lh = addlistener(nc.s,'DataRequired',@(src,event)nc.s.queueOutputData(10*noise));
    nc.s.ScansRequiredFcn = @(src,event)write(nc.s,noise);
    preload(nc.s,noise);
    start(nc.s,"Continuous");
    set(handles.status,'String','Presenting noise clicks');
    disp('Presenting noise clicks')
else
    stop(nc.s);
%     delete(nc.lh);
%     nc.s.IsContinuous = false;
    clear -global nc
    set(handles.status,'String','Stopped noise clicks, now nothing happening');
    disp('Stopped noise clicks')
end











%% BASELINE DURATION
function baselinetime_Callback(hObject, eventdata, handles)
%
function baselinetime_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



%% RESET NIDAQ
function reset_Callback(hObject, eventdata, handles)
daqreset
delete(instrfindall)



%% START PUSH BUTTON
function startbutton_Callback(hObject, eventdata, handles)
clear -global nc
global nc pm
nc.blockN = 1;
nc.mouse = pm.mouse;
nc.stimFolder = pm.stimFolder;
playNextBlock(handles)



%% SAMPLE RATE
function samplerate_Callback(hObject, eventdata, handles)

function samplerate_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


%% FILTER SELECTION
function filterfile_Callback(hObject, eventdata, handles)

function filterfile_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
global pm
set(hObject,'String',[pm.filterFolder '180516_blueAcuteSpeaker_NIDAQ_3k-80k_fs200k.mat'])
pm.filter = get(hObject,'value');

function filterfile_ButtonDownFcn(hObject, eventdata, handles)
global pm
[FileName,PathName] = uigetfile([pm.filterFolder '*.mat'],'Select filter');
if FileName~=0
    set(handles.filterfile,'String',[PathName,FileName]);
end
pm.filter = get(hObject,'value');



%% NIDAQ SETTINGS
function inputN_Callback(hObject, eventdata, handles) % NUMBER OF INPUT CHANNELS
% Hints: get(hObject,'String') returns contents of inputN as text
%        str2double(get(hObject,'String')) returns contents of inputN as a double
function inputN_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function outputN_Callback(hObject, eventdata, handles) % NUMBER OF OUTPUT CHANNELS
function outputN_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function input1_Callback(hObject, eventdata, handles) % 1ST INPUT CHANNEL
function input1_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function output1_Callback(hObject, eventdata, handles)% 1ST OUTPUT CHANNEL
function output1_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function input2_Callback(hObject, eventdata, handles) % 2ND INPUT CHANNEL
function input2_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function output2_Callback(hObject, eventdata, handles) % 2ND OUTPUT CHANNEL
function output2_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function input3_Callback(hObject, eventdata, handles)% 3RD INPUT CHANNEL
function input3_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function output3_Callback(hObject, eventdata, handles)% 3RD OUTPUT CHANNEL
function output3_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


%% QUIT BUTTON
function quitbutton_Callback(hObject, eventdata, handles)
fclose('all');
clear
clear global
close all


%% SAVE CONFIG
function saveconfig_Callback(hObject, eventdata, handles)
global pm
c = cellstr(get(handles.mouselist,'String'));
GUIdata.mouse = c{get(handles.mouselist,'Value')}; % mouse
c = cellstr(get(handles.folderlist,'String'));
GUIdata.person = c{get(handles.folderlist,'Value')}; % person folder
c = cellstr(get(handles.projectlist,'String'));
GUIdata.project = c{get(handles.projectlist,'Value')}; % project folder
c = cellstr(get(handles.stimselectlist,'String'));
GUIdata.stimuli = c;
GUIdata.stimuliFolders = pm.wavFolders; % stimuli full filename
%GUIdata.yaw = get(handles.edit2,'String'); % yaw
%GUIdata.pitch = get(handles.edit1,'String'); % pitch
GUIdata.blockReps = get(handles.blocktable,'Data'); % blocks and repeats
[chanIn,chanOut,nIn,nOut] = getNidaqSettings(handles);
GUIdata.nidaqInfo = {chanIn,chanOut,nIn,nOut};
%GUIdata.recType(1) = get(handles.checkbox1,'Value'); % widefield
%GUIdata.recType(2) = get(handles.checkbox2,'Value'); % 2P
%GUIdata.recType(3) = get(handles.checkbox3,'Value'); % electrophys
GUIdata.baselineDur = get(handles.baselinetime,'String');
%GUIdata.opticalZoom = get(handles.text34,'String');
GUIdata.fs = get(handles.samplerate,'String');
[filename,pathname] = uiputfile([pm.stimFolder GUIdata.person '\' GUIdata.project '\*.mat'],'save configuration');
if ~isempty(pathname)
    save([pathname filename],'GUIdata');
    set(handles.status,'String','Configuration saved');
end





%% LOAD CONFIG
function loadconfig_Callback(hObject, eventdata, handles)
global pm
[filename,pathname]=uigetfile(pm.stimFolder);
load([pathname filename]);
c = cellstr(get(handles.mouselist,'String'));
set(handles.mouselist,'Value',find(strcmp(c,GUIdata.mouse))); % mouse
pm.mouse = GUIdata.mouse;
pm.saveFolder = [pm.mouseFolder pm.mouse '\'];
c = cellstr(get(handles.folderlist,'String'));
set(handles.folderlist,'Value',find(strcmp(c,GUIdata.person))); % person folder
projects = populateProjectFolderListbox(handles);
set(handles.projectlist,'Value',find(strcmp(projects,GUIdata.project))); % project folder
populateSelectStimListbox(handles);
pm.wavFolders = GUIdata.stimuliFolders; % stimuli full filename
set(handles.stimselectlist,'String',GUIdata.stimuli);
set(handles.blocktable,'Data',GUIdata.blockReps); % blocks and repeats
set(handles.inputN,'String',GUIdata.nidaqInfo{3}); % set n channels in
chIn = [13,15,17];
for ii=1:GUIdata.nidaqInfo{3}
    eval(sprintf('set(handles.edit%d,''String'',%d);',chIn(ii),GUIdata.nidaqInfo{1}(ii)))
end
set(handles.outputN,'String',GUIdata.nidaqInfo{4}); % set n channels out
chOut = [14,16,18];
for ii=1:GUIdata.nidaqInfo{4}
    eval(sprintf('set(handles.edit%d,''String'',%d);',chOut(ii),GUIdata.nidaqInfo{2}(ii)))
end


set(handles.baselinetime,'String',GUIdata.baselineDur);
set(handles.samplerate,'String',GUIdata.fs);


%% ABORT BUTTON
function abortbutton_Callback(hObject, eventdata, handles)
global nc pm
% keyboard
if ~isempty(nc)
    if isfield(nc,'s')
        
        stop(nc.s);
        
        % flush current state of card
        nChans = max(size(nc.s.Channels));
        clearStim = zeros(nc.fs*1,nChans);
        write(nc.s,clearStim);
        start(nc.s,"Continuous");
        stop(nc.s);
        
        % clear listeners
        if isfield(nc,'lh')
            delete(nc.lh);
        end
        if isfield(nc,'la')
            delete(nc.la);
        end
        
        % save everything
        exptInfo.mouse = nc.mouse;
        exptInfo.stimFiles = nc.stimFiles;
        b = unique(exptInfo.stimFiles);
        for ii=1:length(b)
            try
                a = load([b{ii}(1:end-4) '_stimInfo.mat']);
                exptInfo.stimInfo{ii} = a;%.stimInfo;
            catch
                exptInfo.stimInfo{ii} = 'Could not find stimInfo';
            end
        end
        exptInfo.preStimSilence = nc.preStimSil;
        exptInfo.fsStim = nc.fs;
        exptInfo.presParams = nc;
        exptInfo.presDirs = pm;
        exptInfo.status = 'ABORTED'; %#ok<STRNU>
        fn = fullfile(pm.saveFolder,[datestr(now,'YYmmdd_HHMMSS') '_exptInfo.mat']);
        save(fn,'exptInfo');
        set(handles.status,'String',['Block ' num2str(nc.blockN) ' of ' num2str(nc.nBlocks) ' saved'])
        
        clear -global nc
        fclose('all');
        set(handles.status,'String','Presentation aborted, nothing happening now');
    else
        set(handles.status,'String','NIDAQ card not initialized, can''t abort!');
    end
end




% --- Executes on button press in pushbutton24.
function pushbutton24_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton24 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)


% --- Executes on button press in pushbutton25.
function pushbutton25_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton25 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)


% --- Creates and returns a handle to the GUI figure. 
function h1 = GoMouse_z_export_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end
load GoMouse_z_export.mat


appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', [], ...
    'taginfo', struct(...
    'figure', 2, ...
    'text', 44, ...
    'listbox', 7, ...
    'checkbox', 4, ...
    'pushbutton', 26, ...
    'uipanel', 10, ...
    'togglebutton', 5, ...
    'edit', 19, ...
    'uitable', 5, ...
    'radiobutton', 3), ...
    'override', 1, ...
    'release', [], ...
    'resize', 'simple', ...
    'accessibility', 'callback', ...
    'mfile', 1, ...
    'callbacks', 1, ...
    'singleton', 1, ...
    'syscolorfig', 1, ...
    'blocking', 0, ...
    'lastSavedFile', 'C:\Users\GeffenLab\Documents\Github\stimulus-gui\GoMouse_z_export.m', ...
    'lastFilename', 'C:\Users\GeffenLab\Documents\Github\stimulus-gui\GoMouse_z.fig');
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = mat{1};

h1 = figure(...
'PaperUnits',get(0,'defaultfigurePaperUnits'),...
'Units','characters',...
'Position',[136.8 26.5384615384615 230.2 57.7692307692308],...
'Visible',get(0,'defaultfigureVisible'),...
'Color',get(0,'defaultfigureColor'),...
'CloseRequestFcn',get(0,'defaultfigureCloseRequestFcn'),...
'CurrentAxesMode','manual',...
'CurrentObjectMode','manual',...
'CurrentPointMode','manual',...
'SelectionTypeMode','manual',...
'ResizeFcn',blanks(0),...
'IntegerHandle','off',...
'NextPlot',get(0,'defaultfigureNextPlot'),...
'Alphamap',get(0,'defaultfigureAlphamap'),...
'Colormap',get(0,'defaultfigureColormap'),...
'WindowButtonDownFcn',blanks(0),...
'WindowButtonUpFcn',blanks(0),...
'WindowButtonMotionFcn',blanks(0),...
'WindowScrollWheelFcn',blanks(0),...
'WindowKeyPressFcn',blanks(0),...
'WindowKeyReleaseFcn',blanks(0),...
'MenuBar','none',...
'ToolBar','none',...
'Pointer',get(0,'defaultfigurePointer'),...
'PointerShapeHotSpot',get(0,'defaultfigurePointerShapeHotSpot'),...
'Name','Untitled',...
'NumberTitle','off',...
'HandleVisibility','callback',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','figure1',...
'UserData',[],...
'WindowStyle',get(0,'defaultfigureWindowStyle'),...
'DockControls',get(0,'defaultfigureDockControls'),...
'Resize',get(0,'defaultfigureResize'),...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'PaperSize',get(0,'defaultfigurePaperSize'),...
'PaperType',get(0,'defaultfigurePaperType'),...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'PaperOrientation',get(0,'defaultfigurePaperOrientation'),...
'ScreenPixelsPerInchMode','manual',...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'text2';

h2 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Go wide mouse!',...
'Style','text',...
'Position',[0.042354474370113 0.932280768499144 0.20742832319722 0.0502821634645869],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Tag','text2',...
'FontSize',22,...
'FontWeight','bold',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text3';

h3 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Mouse:',...
'Style','text',...
'Position',[0.0425716768027802 0.865512649800266 0.0964378801042572 0.033288948069241],...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','text3',...
'FontSize',14);

appdata = [];
appdata.lastValidTag = 'mouselist';

h4 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'ListboxTop',1,...
'ListboxTopMode',get(0,'defaultuicontrolListboxTopMode'),...
'String',{  'K221'; 'K999'; 'NV999' },...
'Style','listbox',...
'Value',3,...
'Position',[0.0425716768027802 0.66577896138482 0.218071242397915 0.202396804260985],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)GoMouse_z_export('mouselist_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GoMouse_z_export('mouselist_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','mouselist',...
'FontSize',12);

appdata = [];
appdata.lastValidTag = 'stimlist';

h5 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',{  'Listbox' },...
'Style','listbox',...
'Value',1,...
'ValueMode',get(0,'defaultuicontrolValueMode'),...
'Position',[0.302345786272806 0.131824234354194 0.174630755864466 0.267643142476698],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)GoMouse_z_export('stimlist_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GoMouse_z_export('stimlist_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','stimlist',...
'KeyPressFcn',blanks(0),...
'FontSize',10.5);

appdata = [];
appdata.lastValidTag = 'text4';

h6 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Select your stimuli:',...
'Style','text',...
'Position',[0.303214596003475 0.399467376830892 0.143353605560382 0.033288948069241],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text4',...
'FontSize',14);

appdata = [];
appdata.lastValidTag = 'text5';

h7 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Stimuli selected:',...
'Style','text',...
'Position',[0.56385751520417 0.399467376830892 0.138140747176368 0.033288948069241],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text5',...
'FontSize',14);

appdata = [];
appdata.lastValidTag = 'addstim';

h8 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Add',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[0.496959165942659 0.33288948069241 0.0460469157254562 0.0492676431424767],...
'Callback',@(hObject,eventdata)GoMouse_z_export('addstim_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','addstim',...
'FontSize',12);

appdata = [];
appdata.lastValidTag = 'removestim';

h9 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Remove',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[0.490877497827976 0.266311584553928 0.0634231103388357 0.0572569906790946],...
'Callback',@(hObject,eventdata)GoMouse_z_export('removestim_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','removestim',...
'KeyPressFcn',blanks(0),...
'FontSize',12);

appdata = [];
appdata.lastValidTag = 'movestimup';

h10 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','move up',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[0.56385751520417 0.0825565912117177 0.0877497827975673 0.0386151797603196],...
'Callback',@(hObject,eventdata)GoMouse_z_export('movestimup_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','movestimup',...
'KeyPressFcn',blanks(0),...
'FontSize',12);

appdata = [];
appdata.lastValidTag = 'movestimdown';

h11 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','move down',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[0.650738488271069 0.0825565912117177 0.0868809730668983 0.0386151797603196],...
'Callback',@(hObject,eventdata)GoMouse_z_export('movestimdown_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','movestimdown',...
'KeyPressFcn',blanks(0),...
'FontSize',12);

appdata = [];
appdata.lastValidTag = 'noiseclicks';

h12 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Noise Clicks',...
'Style','togglebutton',...
'Position',[0.824500434404865 0.679094540612517 0.130321459600348 0.0532623169107856],...
'BackgroundColor',[0 0.45 0.74],...
'Callback',@(hObject,eventdata)GoMouse_z_export('noiseclicks_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',[1 1 1],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','noiseclicks',...
'FontSize',12,...
'FontWeight','bold');

appdata = [];
appdata.lastValidTag = 'folderlist';

h13 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',{  'projects' },...
'Style','listbox',...
'Value',1,...
'Position',[0.0425716768027802 0.400798934753662 0.218071242397915 0.198402130492676],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)GoMouse_z_export('folderlist_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GoMouse_z_export('folderlist_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','folderlist',...
'KeyPressFcn',blanks(0),...
'FontSize',12);

appdata = [];
appdata.lastValidTag = 'text20';

h14 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Folder:',...
'Style','text',...
'Position',[0.0425716768027802 0.599201065246338 0.0964378801042572 0.033288948069241],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text20',...
'FontSize',14);

appdata = [];
appdata.lastValidTag = 'projectlist';

h15 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',{  'Listbox' },...
'Style','listbox',...
'Value',1,...
'ValueMode',get(0,'defaultuicontrolValueMode'),...
'Position',[0.0425716768027802 0.131824234354194 0.218071242397915 0.199733688415446],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)GoMouse_z_export('projectlist_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GoMouse_z_export('projectlist_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','projectlist',...
'KeyPressFcn',blanks(0),...
'FontSize',12);

appdata = [];
appdata.lastValidTag = 'text21';

h16 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Project:',...
'Style','text',...
'Position',[0.0425716768027802 0.33288948069241 0.0964378801042572 0.033288948069241],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text21',...
'FontSize',14);

appdata = [];
appdata.lastValidTag = 'clearstim';

h17 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Clear all',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[0.489139878366638 0.199733688415446 0.0625543006081667 0.0532623169107856],...
'Callback',@(hObject,eventdata)GoMouse_z_export('clearstim_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','clearstim',...
'KeyPressFcn',blanks(0),...
'FontSize',12);

appdata = [];
appdata.lastValidTag = 'reset';

h18 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Reset NIDAQ',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[0.607298001737619 0.679094540612517 0.131190269331017 0.0532623169107856],...
'BackgroundColor',[0.93 0.69 0.13],...
'Callback',@(hObject,eventdata)GoMouse_z_export('reset_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','reset',...
'FontSize',12,...
'FontWeight','bold');

appdata = [];
appdata.lastValidTag = 'randstim';

h19 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Randomise order of stimuli',...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.562119895742832 0.0279627163781625 0.17984361424848 0.0386151797603196],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)GoMouse_z_export('randstim_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','randstim',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',12,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'stimselectlist';

h20 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',{  'Listbox' },...
'Style','listbox',...
'Value',1,...
'Position',[0.56385751520417 0.131824234354194 0.173761946133797 0.267643142476698],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)GoMouse_z_export('stimselectlist_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GoMouse_z_export('stimselectlist_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','stimselectlist',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',10.5,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'blocktable';

h21 = uitable(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuitableFontUnits'),...
'BackgroundColor',[1 1 1;0.941176470588235 0.941176470588235 0.941176470588235],...
'ColumnName',{  'Block'; 'Repeats' },...
'ColumnWidth',{  40 80 },...
'Data',{  blanks(0) blanks(0); blanks(0) blanks(0); blanks(0) blanks(0); blanks(0) blanks(0) },...
'RowName',blanks(0),...
'Position',[0.781059947871416 0.131824234354194 0.174630755864466 0.267643142476698],...
'ColumnEditable',mat{2},...
'ColumnFormat',{  [] [] },...
'RearrangeableColumns',get(0,'defaultuitableRearrangeableColumns'),...
'RowStriping',get(0,'defaultuitableRowStriping'),...
'CellEditCallback',blanks(0),...
'CellSelectionCallback',blanks(0),...
'Children',[],...
'Selection',[],...
'ForegroundColor',get(0,'defaultuitableForegroundColor'),...
'Enable','off',...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuitableVisible'),...
'HandleVisibility',get(0,'defaultuitableHandleVisibility'),...
'ButtonDownFcn',@(hObject,eventdata)GoMouse_z_export('blocktable_ButtonDownFcn',hObject,eventdata,guidata(hObject)),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','blocktable',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuitableFontSize'),...
'FontName',get(0,'defaultuitableFontName'),...
'FontAngle',get(0,'defaultuitableFontAngle'),...
'FontWeight',get(0,'defaultuitableFontWeight'),...
'Layout',[]);

appdata = [];
appdata.lastValidTag = 'uipanel5';

h22 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units',get(0,'defaultuipanelUnits'),...
'Title','Status:',...
'Tag','uipanel5',...
'Position',[0.607298001737619 0.464713715046605 0.347523892267593 0.202396804260985],...
'Layout',[],...
'FontSize',12,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'status';

h23 = uicontrol(...
'Parent',h22,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Select a mouse!',...
'Style','text',...
'Position',[0.0631578947368421 0.190839694656489 0.866666666666667 0.679389312977099],...
'Children',[],...
'Tag','status',...
'FontSize',12,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'quitbutton';

h24 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Quit',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[0.867072111207645 0.878828229027963 0.0877497827975673 0.0532623169107856],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)GoMouse_z_export('quitbutton_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','quitbutton',...
'KeyPressFcn',blanks(0),...
'FontSize',12,...
'FontWeight','bold');

appdata = [];
appdata.lastValidTag = 'saveconfig';

h25 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Save configuration',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[0.303214596003475 0.0279627163781625 0.131190269331017 0.0386151797603196],...
'Callback',@(hObject,eventdata)GoMouse_z_export('saveconfig_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','saveconfig',...
'KeyPressFcn',blanks(0),...
'FontSize',12);

appdata = [];
appdata.lastValidTag = 'loadconfig';

h26 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Load configuration',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[0.303214596003475 0.0838881491344874 0.131190269331017 0.0386151797603196],...
'Callback',@(hObject,eventdata)GoMouse_z_export('loadconfig_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','loadconfig',...
'KeyPressFcn',blanks(0),...
'FontSize',12);

appdata = [];
appdata.lastValidTag = 'abortbutton';

h27 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','ABORT',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[0.867072111207645 0.745672436750999 0.0877497827975673 0.0532623169107856],...
'BackgroundColor',[1 0 0],...
'Callback',@(hObject,eventdata)GoMouse_z_export('abortbutton_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',[1 1 1],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','abortbutton',...
'KeyPressFcn',blanks(0),...
'FontSize',16,...
'FontWeight','bold');

appdata = [];
appdata.lastValidTag = 'startbutton';

h28 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','START',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[0.867072111207645 0.812250332889481 0.0877497827975673 0.0532623169107856],...
'BackgroundColor',[0.47 0.67 0.19],...
'Callback',@(hObject,eventdata)GoMouse_z_export('startbutton_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',[1 1 1],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','startbutton',...
'KeyPressFcn',blanks(0),...
'FontSize',16,...
'FontWeight','bold');

appdata = [];
appdata.lastValidTag = 'uipanel2';

h29 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units',get(0,'defaultuipanelUnits'),...
'ForegroundColor',get(0,'defaultuipanelForegroundColor'),...
'HighlightColor',get(0,'defaultuipanelHighlightColor'),...
'ShadowColor',get(0,'defaultuipanelShadowColor'),...
'BorderType',get(0,'defaultuipanelBorderType'),...
'BorderWidth',get(0,'defaultuipanelBorderWidth'),...
'TitlePosition',get(0,'defaultuipanelTitlePosition'),...
'Title','Presentation Information:',...
'Visible',get(0,'defaultuipanelVisible'),...
'BackgroundColor',get(0,'defaultuipanelBackgroundColor'),...
'ResizeFcn',blanks(0),...
'HandleVisibility',get(0,'defaultuipanelHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uipanel2',...
'UserData',[],...
'Position',[0.303214596003475 0.760319573901465 0.523892267593397 0.171770972037284],...
'Layout',[],...
'FontSize',12,...
'FontName',get(0,'defaultuipanelFontName'),...
'FontAngle',get(0,'defaultuipanelFontAngle'),...
'FontWeight',get(0,'defaultuipanelFontWeight'));

appdata = [];
appdata.lastValidTag = 'text29';

h30 = uicontrol(...
'Parent',h29,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Sample rate:',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.175475687103594 0.469026548672566 0.207188160676533 0.185840707964602],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text29',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',12,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'samplerate';

h31 = uicontrol(...
'Parent',h29,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','200000',...
'Style','edit',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.40169133192389 0.469026548672566 0.526427061310782 0.194690265486726],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)GoMouse_z_export('samplerate_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GoMouse_z_export('samplerate_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','samplerate',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',12,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'filterfile';

h32 = uicontrol(...
'Parent',h29,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','D:\GitHub\filters\180516_blueAcuteSpeaker_NIDAQ_3k-80k_fs200k.mat',...
'Style','edit',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.147991543340381 0.743362831858407 0.822410147991543 0.194690265486726],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)GoMouse_z_export('filterfile_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable','off',...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',@(hObject,eventdata)GoMouse_z_export('filterfile_ButtonDownFcn',hObject,eventdata,guidata(hObject)),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GoMouse_z_export('filterfile_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','filterfile',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text14';

h33 = uicontrol(...
'Parent',h29,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Baseline duration (s):',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0591966173361522 0.194690265486726 0.325581395348837 0.238938053097345],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text14',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',12,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'baselinetime';

h34 = uicontrol(...
'Parent',h29,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','5',...
'Style','edit',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.40169133192389 0.247787610619469 0.526427061310782 0.194690265486726],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)GoMouse_z_export('baselinetime_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GoMouse_z_export('baselinetime_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','baselinetime',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',12,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text30';

h35 = uicontrol(...
'Parent',h29,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Filter:',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0183639398998331 0.747747747747748 0.110183639398998 0.189189189189189],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text30',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',12,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'uipanel8';

h36 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units',get(0,'defaultuipanelUnits'),...
'ForegroundColor',get(0,'defaultuipanelForegroundColor'),...
'HighlightColor',get(0,'defaultuipanelHighlightColor'),...
'ShadowColor',get(0,'defaultuipanelShadowColor'),...
'BorderType',get(0,'defaultuipanelBorderType'),...
'BorderWidth',get(0,'defaultuipanelBorderWidth'),...
'TitlePosition',get(0,'defaultuipanelTitlePosition'),...
'Title','NIDAQ Settings',...
'Visible',get(0,'defaultuipanelVisible'),...
'BackgroundColor',get(0,'defaultuipanelBackgroundColor'),...
'ResizeFcn',blanks(0),...
'HandleVisibility',get(0,'defaultuipanelHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uipanel8',...
'UserData',[],...
'Position',[0.303214596003475 0.462050599201065 0.132927888792354 0.270306258322237],...
'Layout',[],...
'FontSize',12,...
'FontName',get(0,'defaultuipanelFontName'),...
'FontAngle',get(0,'defaultuipanelFontAngle'),...
'FontWeight',get(0,'defaultuipanelFontWeight'));

appdata = [];
appdata.lastValidTag = 'inputN';

h37 = uicontrol(...
'Parent',h36,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','0',...
'Style','edit',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.23963133640553 0.644808743169399 0.235023041474654 0.120218579234973],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)GoMouse_z_export('inputN_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GoMouse_z_export('inputN_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','inputN',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text37';

h38 = uicontrol(...
'Parent',h36,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Input Channels',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.184100418410042 0.8 0.343096234309623 0.143333333333333],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text37',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'outputN';

h39 = uicontrol(...
'Parent',h36,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','3',...
'Style','edit',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.631336405529954 0.644808743169399 0.235023041474654 0.120218579234973],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)GoMouse_z_export('outputN_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GoMouse_z_export('outputN_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','outputN',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text38';

h40 = uicontrol(...
'Parent',h36,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Output Channels',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.552301255230126 0.796666666666667 0.389121338912134 0.146666666666667],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text38',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'input1';

h41 = uicontrol(...
'Parent',h36,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style','edit',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.23963133640553 0.469945355191257 0.235023041474654 0.120218579234973],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)GoMouse_z_export('input1_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GoMouse_z_export('input1_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','input1',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'output1';

h42 = uicontrol(...
'Parent',h36,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','0',...
'Style','edit',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.631336405529954 0.469945355191257 0.235023041474654 0.120218579234973],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)GoMouse_z_export('output1_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GoMouse_z_export('output1_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','output1',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text40';

h43 = uicontrol(...
'Parent',h36,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','1st',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0414746543778802 0.46207650273224 0.184331797235023 0.109289617486339],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text40',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',10,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'input2';

h44 = uicontrol(...
'Parent',h36,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style','edit',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.23963133640553 0.295081967213115 0.235023041474654 0.120218579234973],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)GoMouse_z_export('input2_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GoMouse_z_export('input2_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','input2',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'output2';

h45 = uicontrol(...
'Parent',h36,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','1',...
'Style','edit',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.631336405529954 0.295081967213115 0.235023041474654 0.120218579234973],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)GoMouse_z_export('output2_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GoMouse_z_export('output2_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','output2',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text41';

h46 = uicontrol(...
'Parent',h36,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','2nd',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0276497695852535 0.287213114754098 0.193548387096774 0.109289617486339],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text41',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',10,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'input3';

h47 = uicontrol(...
'Parent',h36,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style','edit',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.23963133640553 0.109289617486339 0.235023041474654 0.120218579234973],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)GoMouse_z_export('input3_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GoMouse_z_export('input3_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','input3',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'output3';

h48 = uicontrol(...
'Parent',h36,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','2',...
'Style','edit',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.631336405529954 0.109289617486339 0.235023041474654 0.120218579234973],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)GoMouse_z_export('output3_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GoMouse_z_export('output3_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','output3',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text42';

h49 = uicontrol(...
'Parent',h36,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','3rd',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.032258064516129 0.101420765027322 0.188940092165899 0.109289617486339],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text42',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',10,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text39';

h50 = uicontrol(...
'Parent',h36,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','n',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0875576036866359 0.643606557377049 0.138248847926267 0.109289617486339],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text39',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',10,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text43';

h51 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Blocks:',...
'Style','text',...
'Position',[0.781059947871416 0.400798934753662 0.0860121633362294 0.033288948069241],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text43',...
'FontSize',14);

appdata = [];
appdata.lastValidTag = 'uipanel9';

h52 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units',get(0,'defaultuipanelUnits'),...
'Title','LEDs',...
'Tag','uipanel9',...
'Position',[0.454387489139878 0.466045272969374 0.131190269331017 0.267643142476698],...
'Layout',[],...
'FontSize',12,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'pushbutton24';

h53 = uicontrol(...
'Parent',h52,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','GREEN',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[0.165957446808511 0.546979865771812 0.727659574468085 0.231543624161074],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)GoMouse_z_export('pushbutton24_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',[0.290196078431373 0.529411764705882 0.0156862745098039],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','pushbutton24',...
'FontSize',14,...
'FontWeight','bold');

appdata = [];
appdata.lastValidTag = 'pushbutton25';

h54 = uicontrol(...
'Parent',h52,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','RED',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[0.157446808510638 0.174496644295302 0.727659574468085 0.231543624161074],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)GoMouse_z_export('pushbutton25_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',[0.635294117647059 0.0784313725490196 0.184313725490196],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton25',...
'KeyPressFcn',blanks(0),...
'FontSize',14,...
'FontWeight','bold');


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end


% --- Handles default GUIDE GUI creation and callback dispatch
function varargout = gui_mainfcn(gui_State, varargin)

gui_StateFields =  {'gui_Name'
    'gui_Singleton'
    'gui_OpeningFcn'
    'gui_OutputFcn'
    'gui_LayoutFcn'
    'gui_Callback'};
gui_Mfile = '';
for i=1:length(gui_StateFields)
    if ~isfield(gui_State, gui_StateFields{i})
        error(message('MATLAB:guide:StateFieldNotFound', gui_StateFields{ i }, gui_Mfile));
    elseif isequal(gui_StateFields{i}, 'gui_Name')
        gui_Mfile = [gui_State.(gui_StateFields{i}), '.m'];
    end
end

numargin = length(varargin);

if numargin == 0
    % GOMOUSE_Z_EXPORT
    % create the GUI only if we are not in the process of loading it
    % already
    gui_Create = true;
elseif local_isInvokeActiveXCallback(gui_State, varargin{:})
    % GOMOUSE_Z_EXPORT(ACTIVEX,...)
    vin{1} = gui_State.gui_Name;
    vin{2} = [get(varargin{1}.Peer, 'Tag'), '_', varargin{end}];
    vin{3} = varargin{1};
    vin{4} = varargin{end-1};
    vin{5} = guidata(varargin{1}.Peer);
    feval(vin{:});
    return;
elseif local_isInvokeHGCallback(gui_State, varargin{:})
    % GOMOUSE_Z_EXPORT('CALLBACK',hObject,eventData,handles,...)
    gui_Create = false;
else
    % GOMOUSE_Z_EXPORT(...)
    % create the GUI and hand varargin to the openingfcn
    gui_Create = true;
end

if ~gui_Create
    % In design time, we need to mark all components possibly created in
    % the coming callback evaluation as non-serializable. This way, they
    % will not be brought into GUIDE and not be saved in the figure file
    % when running/saving the GUI from GUIDE.
    designEval = false;
    if (numargin>1 && ishghandle(varargin{2}))
        fig = varargin{2};
        while ~isempty(fig) && ~ishghandle(fig,'figure')
            fig = get(fig,'parent');
        end
        
        designEval = isappdata(0,'CreatingGUIDEFigure') || (isscalar(fig)&&isprop(fig,'GUIDEFigure'));
    end
        
    if designEval
        beforeChildren = findall(fig);
    end
    
    % evaluate the callback now
    varargin{1} = gui_State.gui_Callback;
    if nargout
        [varargout{1:nargout}] = feval(varargin{:});
    else       
        feval(varargin{:});
    end
    
    % Set serializable of objects created in the above callback to off in
    % design time. Need to check whether figure handle is still valid in
    % case the figure is deleted during the callback dispatching.
    if designEval && ishghandle(fig)
        set(setdiff(findall(fig),beforeChildren), 'Serializable','off');
    end
else
    if gui_State.gui_Singleton
        gui_SingletonOpt = 'reuse';
    else
        gui_SingletonOpt = 'new';
    end

    % Check user passing 'visible' P/V pair first so that its value can be
    % used by oepnfig to prevent flickering
    gui_Visible = 'auto';
    gui_VisibleInput = '';
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        % Recognize 'visible' P/V pair
        len1 = min(length('visible'),length(varargin{index}));
        len2 = min(length('off'),length(varargin{index+1}));
        if ischar(varargin{index+1}) && strncmpi(varargin{index},'visible',len1) && len2 > 1
            if strncmpi(varargin{index+1},'off',len2)
                gui_Visible = 'invisible';
                gui_VisibleInput = 'off';
            elseif strncmpi(varargin{index+1},'on',len2)
                gui_Visible = 'visible';
                gui_VisibleInput = 'on';
            end
        end
    end
    
    % Open fig file with stored settings.  Note: This executes all component
    % specific CreateFunctions with an empty HANDLES structure.

    
    % Do feval on layout code in m-file if it exists
    gui_Exported = ~isempty(gui_State.gui_LayoutFcn);
    % this application data is used to indicate the running mode of a GUIDE
    % GUI to distinguish it from the design mode of the GUI in GUIDE. it is
    % only used by actxproxy at this time.   
    setappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]),1);
    if gui_Exported
        gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

        % make figure invisible here so that the visibility of figure is
        % consistent in OpeningFcn in the exported GUI case
        if isempty(gui_VisibleInput)
            gui_VisibleInput = get(gui_hFigure,'Visible');
        end
        set(gui_hFigure,'Visible','off')

        % openfig (called by local_openfig below) does this for guis without
        % the LayoutFcn. Be sure to do it here so guis show up on screen.
        movegui(gui_hFigure,'onscreen');
    else
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        % If the figure has InGUIInitialization it was not completely created
        % on the last pass.  Delete this handle and try again.
        if isappdata(gui_hFigure, 'InGUIInitialization')
            delete(gui_hFigure);
            gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        end
    end
    if isappdata(0, genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]))
        rmappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]));
    end

    % Set flag to indicate starting GUI initialization
    setappdata(gui_hFigure,'InGUIInitialization',1);

    % Fetch GUIDE Application options
    gui_Options = getappdata(gui_hFigure,'GUIDEOptions');
    % Singleton setting in the GUI MATLAB code file takes priority if different
    gui_Options.singleton = gui_State.gui_Singleton;

    if ~isappdata(gui_hFigure,'GUIOnScreen')
        % Adjust background color
        if gui_Options.syscolorfig
            set(gui_hFigure,'Color', get(0,'DefaultUicontrolBackgroundColor'));
        end

        % Generate HANDLES structure and store with GUIDATA. If there is
        % user set GUI data already, keep that also.
        data = guidata(gui_hFigure);
        handles = guihandles(gui_hFigure);
        if ~isempty(handles)
            if isempty(data)
                data = handles;
            else
                names = fieldnames(handles);
                for k=1:length(names)
                    data.(char(names(k)))=handles.(char(names(k)));
                end
            end
        end
        guidata(gui_hFigure, data);
    end

    % Apply input P/V pairs other than 'visible'
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        len1 = min(length('visible'),length(varargin{index}));
        if ~strncmpi(varargin{index},'visible',len1)
            try set(gui_hFigure, varargin{index}, varargin{index+1}), catch break, end
        end
    end

    % If handle visibility is set to 'callback', turn it on until finished
    % with OpeningFcn
    gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
    if strcmp(gui_HandleVisibility, 'callback')
        set(gui_hFigure,'HandleVisibility', 'on');
    end

    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        % Handle the default callbacks of predefined toolbar tools in this
        % GUI, if any
        guidemfile('restoreToolbarToolPredefinedCallback',gui_hFigure); 
        
        % Update handle visibility
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);

        % Call openfig again to pick up the saved visibility or apply the
        % one passed in from the P/V pairs
        if ~gui_Exported
            gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);
        elseif ~isempty(gui_VisibleInput)
            set(gui_hFigure,'Visible',gui_VisibleInput);
        end
        if strcmpi(get(gui_hFigure, 'Visible'), 'on')
            figure(gui_hFigure);
            
            if gui_Options.singleton
                setappdata(gui_hFigure,'GUIOnScreen', 1);
            end
        end

        % Done with GUI initialization
        if isappdata(gui_hFigure,'InGUIInitialization')
            rmappdata(gui_hFigure,'InGUIInitialization');
        end

        % If handle visibility is set to 'callback', turn it on until
        % finished with OutputFcn
        gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
        if strcmp(gui_HandleVisibility, 'callback')
            set(gui_hFigure,'HandleVisibility', 'on');
        end
        gui_Handles = guidata(gui_hFigure);
    else
        gui_Handles = [];
    end

    if nargout
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    else
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    end

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);
    end
end

function gui_hFigure = local_openfig(name, singleton, visible)

% openfig with three arguments was new from R13. Try to call that first, if
% failed, try the old openfig.
if nargin('openfig') == 2
    % OPENFIG did not accept 3rd input argument until R13,
    % toggle default figure visible to prevent the figure
    % from showing up too soon.
    gui_OldDefaultVisible = get(0,'defaultFigureVisible');
    set(0,'defaultFigureVisible','off');
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton);
    set(0,'defaultFigureVisible',gui_OldDefaultVisible);
else
    % Call version of openfig that accepts 'auto' option"
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);  
%     %workaround for CreateFcn not called to create ActiveX
%         peers=findobj(findall(allchild(gui_hFigure)),'type','uicontrol','style','text');    
%         for i=1:length(peers)
%             if isappdata(peers(i),'Control')
%                 actxproxy(peers(i));
%             end            
%         end
end

function result = local_isInvokeActiveXCallback(gui_State, varargin)

try
    result = ispc && iscom(varargin{1}) ...
             && isequal(varargin{1},gcbo);
catch
    result = false;
end

function result = local_isInvokeHGCallback(gui_State, varargin)

try
    fhandle = functions(gui_State.gui_Callback);
    result = ~isempty(findstr(gui_State.gui_Name,fhandle.file)) || ...
             (ischar(varargin{1}) ...
             && isequal(ishghandle(varargin{2}), 1) ...
             && (~isempty(strfind(varargin{1},[get(varargin{2}, 'Tag'), '_'])) || ...
                ~isempty(strfind(varargin{1}, '_CreateFcn'))) );
catch
    result = false;
end


